---

title: "Documentation_2"
output: 
  html_document: {toc: true, toc_float: true,
  toc_depth: 2}
  
---

# PEP Project

## Map of stations
```{r, message=FALSE, echo=FALSE, warning=FALSE}
 library(sf)
 library(SWMPr)
 library(tidyverse)
 library(ggrepel)
 library(raster)
 install.packages(rgdal)
 library(rgdal)


 grb.codes <- SWMPr::site_codes() %>%
   dplyr::filter(nerr_site_id == c("grb"))
 nar.codes <- SWMPr::site_codes() %>%
   dplyr::filter(nerr_site_id == c("nar"))
 wel.codes <- SWMPr::site_codes() %>%
   dplyr::filter(nerr_site_id == c("wel"))
 wqb.codes <- SWMPr::site_codes() %>%
   dplyr::filter(nerr_site_id == c("wqb"))

 codes <- rbind(grb.codes, nar.codes, wel.codes, wqb.codes) %>%
   dplyr::mutate(latitude = as.numeric(latitude),#
                  longitude = as.numeric(longitude)*-1)
 
 site_labels <- codes %>%
   group_by(reserve_name) %>%
   slice(1)

 crs <- "+proj=longlat +lat_1=35 +lat_2=45 +lat_0=40 +lon_0=-77+x_0=0
 +y_0=0 +datum=NAD83 +no_defs +ellps=GRS80 +towgs84=0,0,0"
 coast_shp <- rgdal::readOGR(file.path(here::here("data-raw","coast", "USA.shp")), verbose = F)
 crs(coast_shp) <- crs
 coast_sf <- as(coast_shp, "sf")

 xmin = -72
 xmax = -69
 ymin = 41
 ymax = 44
 xlims <- c(xmin, xmax)
 ylims <- c(ymin, ymax)
 crs <- "+proj=longlat +lat_1=35 +lat_2=45 +lat_0=40 +lon_0=-77 +x_0=0 +y_0=0 +datum=NAD83 +no_defs +ellps=GRS80 +towgs84=0,0,0"
 m <- ggplot()+
   ggplot2::geom_sf(data = coast_sf) +
   ggplot2::coord_sf(crs = crs, xlim = xlims, ylim = ylims)+
   geom_point(aes(longitude, latitude), data = site_labels, color = "midnightblue", size = 2)+
   geom_label_repel(data = site_labels, aes( longitude, latitude, label = reserve_name),
                    size = 3)
 xbreaks <- seq(-72, -69, 1)
 ybreaks <- pretty(codes$latitude)
 xlabels <- paste0(abs(xbreaks), "°W")
 ylabels <- paste0(abs(ybreaks), "°N")
 m + scale_x_continuous(breaks = xbreaks, labels = xlabels)+
   scale_y_continuous(breaks = ybreaks, labels = ylabels)+
      labs(x = NULL, y = NULL, title = "NERRs - New England Sites")
```

## Dissolved Oxygen (mg/L) {.tabset}

### All years

``` {r, message=FALSE, echo=FALSE, warning=FALSE, figures-side, fig.show="hold", out.width="50%"}
library(tidyverse)
raw.dir <- here::here("data")
daily_csv <-"water_quality_pep.csv"
daily <- read_csv(file.path(raw.dir,daily_csv))

rmdomgl<-daily %>% group_by(station) %>% 
  filter(Variable == "DO_mgl" & mean_daily > 0 & mean_daily < 15)

rmdopct<-daily %>% group_by(station) %>% 
  filter(Variable == "DO_Pct" & mean_daily > 50 & mean_daily < 120 ) 

rmtemp<-daily %>% group_by(station) %>% 
  filter(Variable == "Temp" & mean_daily > 0 & mean_daily < 30 )

rmsal<-daily %>% group_by(station) %>% 
  filter(Variable == "Sal" & mean_daily > 0 & mean_daily < 32 )

monthly <- rbind(rmdomgl, rmdopct, rmtemp, rmsal)

nartsmonth <- monthly %>% filter(station == "nartswq")
waqmonth <- monthly %>% filter(station == "wqbmpwq")
welmonth <- monthly %>% filter(station == "welinwq")
grbmonth <- monthly %>% filter(station == "grbgbwq") %>% 
mutate(date = as.Date(date)) 

nartsmonth %>% 
  filter(Variable == "DO_mgl") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 15)+
  labs(x = "Year", y = "Dissolved Oxygen Concentration (mg/L)", title = "Narraganset")+
  ecodata::theme_ts()

grbmonth %>% 
  filter(Variable == "DO_mgl") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 15)+
  labs(x = "Year", y = "Dissolved Oxygen Concentration (mg/L)", title = "Great Bay")+
  ecodata::theme_ts()

waqmonth %>% 
  filter(Variable == "DO_mgl") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 15)+
  labs(x = "Year", y = "Dissolved Oxygen Concentration (mg/L)", title = "Waquoit Bay")+
  ecodata::theme_ts()

welmonth %>% 
  filter(Variable == "DO_mgl") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 15)+
  labs(x = "Year", y = "Dissolved Oxygen Concentration (mg/L)", title = "Wells Bay")+
  ecodata::theme_ts()
```

### Only 2020

``` {r, message=FALSE, echo=FALSE, warning=FALSE, fig.show="hold", out.width="50%"}
nartsmonth %>% 
  filter(Variable == "DO_mgl") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(0, 15)+
  labs(x = "", y = "Dissolved Oxygen Concentration (mg/L)", title = "Narraganset")+
  ecodata::theme_ts()

grbmonth %>% 
  filter(Variable == "DO_mgl") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(0, 15)+
  labs(x = "", y = "Dissolved Oxygen Concentration (mg/L)", title = "Great Bay")+
  ecodata::theme_ts()

waqmonth %>% 
  filter(Variable == "DO_mgl") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(0, 15)+
  labs(x = "", y = "Dissolved Oxygen Concentration (mg/L)", title = "Waquoit Bay")+
  ecodata::theme_ts()

welmonth %>% 
  filter(Variable == "DO_mgl") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(0, 15)+
  labs(x = "", y = "Dissolved Oxygen Concentration (mg/L)", title = "Wells Bay")+
  ecodata::theme_ts()
```

## Dissolved Oxygen (%) {.tabset}

### All years

``` {r, message=FALSE, echo=FALSE, warning=FALSE, fig.show="hold", out.width="50%"}
nartsmonth %>% 
  filter(Variable == "DO_Pct") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(50, 120)+
  labs(x = "Year", y = "Dissolved Oxygen Concentration (% saturation)", title = "Narraganset") +
  ecodata::theme_ts()

grbmonth %>% 
  filter(Variable == "DO_Pct") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(50, 120)+
  labs(x = "Year", y = "Dissolved Oxygen Concentration (% saturation)", title = "Great Bay") +
  ecodata::theme_ts()

waqmonth %>% 
  filter(Variable == "DO_Pct") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(50, 120)+
  labs(x = "Year", y = "Dissolved Oxygen Concentration (% saturation)", title = "Waquoit Bay") +
  ecodata::theme_ts()

welmonth %>% 
  filter(Variable == "DO_Pct") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(50, 120)+
  labs(x = "Year", y = "Dissolved Oxygen Concentration (% saturation)", title = "Wells Bay") +
  ecodata::theme_ts()
```

### Only 2020

```{r, message=FALSE, echo=FALSE, warning=FALSE, fig.show="hold", out.width="50%"}
nartsmonth %>% 
  filter(Variable == "DO_Pct") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(50, 120)+
  labs(x = "", y = "Dissolved Oxygen Concentration (% saturation)", title = "Narraganset")+
  ecodata::theme_ts()

grbmonth %>% 
  filter(Variable == "DO_Pct") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(50, 120)+
  labs(x = "", y = "Dissolved Oxygen Concentration (% saturation)", title = "Great Bay")+
  ecodata::theme_ts()

waqmonth %>% 
  filter(Variable == "DO_Pct") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(50, 120)+
  labs(x = "", y = "Dissolved Oxygen Concentration (% saturation)", title = "Waquoit Bay")+
  ecodata::theme_ts()

welmonth %>% 
  filter(Variable == "DO_Pct") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(50, 120)+
  labs(x = "", y = "Dissolved Oxygen Concentration (% saturation)", title = "Wells Bay")+
  ecodata::theme_ts()
```

## Temperature {.tabset}

### All years

``` {r, message=FALSE, echo=FALSE, warning=FALSE, fig.show="hold", out.width="50%"}
nartsmonth %>% 
  filter(Variable == "Temp") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 30)+
  labs(x = "Year", y = "Temperature (C)", title = "Narraganset")+
  ecodata::theme_ts()

grbmonth %>% 
  filter(Variable == "Temp") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 30)+
  labs(x = "Year", y = "Temperature (C)", title = "Great Bay")+
  ecodata::theme_ts()

waqmonth %>% 
  filter(Variable == "Temp") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 30)+
  labs(x = "Year", y = "Temperature (C)", title = "Waquoit Bay")+
  ecodata::theme_ts()

welmonth %>% 
  filter(Variable == "Temp") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 30)+
  labs(x = "Year", y = "Temperature (C)", title = "Wells Bay")+
  ecodata::theme_ts()
```

### Only 2020

``` {r, message=FALSE, echo=FALSE, warning=FALSE, fig.show="hold", out.width="50%"}
nartsmonth %>% 
  filter(Variable == "Temp") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(0, 30)+
  labs(x = "", y = "Temperature (C)", title = "Narraganset")+
  ecodata::theme_ts()

grbmonth %>% 
  filter(Variable == "Temp") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(0, 30)+
  labs(x = "", y = "Temperature (C)", title = "Great Bay")+
  ecodata::theme_ts()

waqmonth %>% 
  filter(Variable == "Temp") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(0, 30)+
  labs(x = "", y = "Temperature (C)", title = "Waquoit Bay")+
  ecodata::theme_ts()

welmonth %>% 
  filter(Variable == "Temp") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(0, 30)+
  labs(x = "", y = "Temperature (C)", title = "Wells Bay")+
  ecodata::theme_ts()
```

## Salinity {.tabset}

### All years

``` {r, message=FALSE, echo=FALSE, warning=FALSE, fig.show="hold", out.width="50%"}
nartsmonth %>% 
  filter(Variable == "Sal") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 32)+
  labs(x = "Year", y = "Salnity (psu)", title = "Narraganset")+
  ecodata::theme_ts()

grbmonth %>% 
  filter(Variable == "Sal") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 32)+
  labs(x = "Year", y = "Salnity (psu)", title = "Great Bay")+
  ecodata::theme_ts()

waqmonth %>% 
  filter(Variable == "Sal") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 32)+
  labs(x = "Year", y = "Salnity (psu)", title = "Waquoit Bay")+
  ecodata::theme_ts()

welmonth %>% 
  filter(Variable == "Sal") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 32)+
  labs(x = "Year", y = "Salnity (psu)", title = "Wells Bay")+
  ecodata::theme_ts()
```

### Only 2020

```{r, message=FALSE, echo=FALSE, warning=FALSE, fig.show="hold", out.width="50%"}
nartsmonth %>% 
  filter(Variable == "Sal") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(0, 32)+
  labs(x = "", y = "Salinity (psu)", title = "Narraganset")+
  ecodata::theme_ts()

grbmonth %>% 
  filter(Variable == "Sal") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(0, 32)+
  labs(x = "", y = "Salinity (psu)", title = "Great Bay")+
  ecodata::theme_ts()

waqmonth %>% 
  filter(Variable == "Sal") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(0, 32)+
  labs(x = "", y = "Salinity (psu)", title = "Waquoit Bay")+
  ecodata::theme_ts()

welmonth %>% 
  filter(Variable == "Sal") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(0, 32)+
  labs(x = "", y = "Salinity (psu)", title = "Wells Bay")+
  ecodata::theme_ts()
```

## Chlorophyll

```{r, message=FALSE, echo=FALSE, warning=FALSE, fig.show="hold", out.width="50%"}
chloro_nutri <- read_csv(here::here("data/nutrient_pep.csv"))
nartsnut <- chloro_nutri %>% filter(station == "nartsnut")
welnut <- chloro_nutri %>% filter(station == "welinnut")
grbnut <- chloro_nutri %>% filter(station == "grbgbnut") %>%
  mutate(date = as.Date(date))

nartsnut%>% 
  filter(Variable == "CHLA_N") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "purple", size = 2)+
  #geom_smooth(method = "loess", span = 0.15, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 10)+
  labs(x = "Year", y = "Chlorophyll concentration (µg/L)", title = "Narraganset")+
  ecodata::theme_ts()

grbnut%>% 
  filter(Variable == "CHLA_N") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "purple", size = 2)+
  #geom_smooth(method = "loess", span = 0.50, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 10)+
  labs(x = "Year", y = "Chlorophyll concentration (µg/L)", title = "Great Bay")+
  ecodata::theme_ts()

welnut%>% 
  filter(Variable == "CHLA_N") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "purple", size = 2)+
  #geom_smooth(method = "loess", span = 0.15, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 10)+
  labs(x = "Year", y = "Chlorophyll concentration (µg/L)", title = "Wells Bay")+
  ecodata::theme_ts()
```