---

title: "Documentation_2"
output: 
  html_document: {toc: true, toc_float: true,
  toc_depth: 2}
  
---

# PEP Project

## Dissolved Oxygen (mg/L) {.tabset}

### All years

``` {r, message=FALSE, echo=FALSE, warning=FALSE, figures-side, fig.show="hold", out.width="50%"}
# library(tidyverse)
library(dplyr)
library(tidyr)
library(ggplot2)
library(readr)
library(SWMPr)
# remotes::install_github("NOAA-EDAB/ecodata")

raw_dat <- bind_rows(
  import_local(here::here("data-raw/wq"), station_code = "nartswq") %>% 
    qaqc() %>% 
    mutate(station = "nartswq"),
  import_local(here::here("data-raw/wq"), station_code = "wqbmpwq") %>% 
    qaqc() %>% 
    mutate(station = "wqbmpwq"),
  import_local(here::here("data-raw/wq"), station_code = "welinwq") %>% 
    qaqc() %>% 
    mutate(station = "welinwq"),
  import_local(here::here("data-raw/wq"), station_code = "grbgbwq") %>% 
    qaqc() %>% 
    mutate(station = "grbgbwq"))


daily <- raw_dat %>% 
  mutate(date = format(as.Date(datetimestamp), "%Y-%m-%d")) %>%
  select(date,
         station,
         Temp = temp, 
         Sal = sal, 
         DO_Pct = do_pct, 
         DO_mgl = do_mgl) %>%
  pivot_longer(cols = c("Temp", "Sal", "DO_Pct", "DO_mgl"), names_to = "Variable", values_to = "value") %>% 
  group_by(station, Variable, date) %>%
  summarize(mean_daily = mean(value, na.rm = TRUE),
            mean_daily = ifelse(is.nan(mean_daily),
                               NA_real_,
                               mean_daily))

# raw.dir <- here::here("data")
# daily_csv <-"water_quality_pep.csv"
# daily <- read_csv(file.path(raw.dir,daily_csv))

rmdomgl<-daily %>% group_by(station) %>%
  filter(Variable == "DO_mgl" & mean_daily > 0 & mean_daily < 15 | is.na(mean_daily))

rmdopct<-daily %>% group_by(station) %>%
  filter(Variable == "DO_Pct" & mean_daily > 50 & mean_daily < 120 | is.na(mean_daily))

rmtemp<-daily %>% group_by(station) %>%
  filter(Variable == "Temp" & mean_daily > 0 & mean_daily < 30 | is.na(mean_daily))

rmsal<-daily %>% group_by(station) %>%
  filter(Variable == "Sal" & mean_daily > 0 & mean_daily < 32 | is.na(mean_daily))

monthly <- rbind(rmdomgl, rmdopct, rmtemp, rmsal)

# nartsmonth <- monthly %>% filter(station == "nartswq")
# waqmonth <- monthly %>% filter(station == "wqbmpwq")
# welmonth <- monthly %>% filter(station == "welinwq")
# grbmonth <- monthly %>% filter(station == "grbgbwq") %>%
# mutate(date = as.Date(date))

station_names <- as_labeller(
     c('nartswq' = "Narragansett",
       "wqbmpwq"= "Waquoit Bay",
       "welinwq" = "Wells Bay", 
       "grbgbwq" = "Great Bay"))

## grp takes the non-NA for each station, month, and variable and creates a "group" (1, 2, 3, ...)
## counter takes the number of rows for each station, month, and variable
## the first mutate "mean_month" takes all of the data with a maximum count < 10 for each group and makes "NA", otherwise it takes the mean.
## If you try to take the mean of all NAs, it creates a "NaN", which is not exactly like


dat_month <- monthly %>%
  mutate(month_year = format(as.Date(date), "%Y-%m")) %>%
  group_by(station, month_year, Variable, grp = with(rle(!is.na(mean_daily)), 
                                                     rep(seq_along(lengths),
                                                         lengths))) %>%
  mutate(counter = 1:n()) %>%
  ungroup() %>%
  select(-grp) %>%
  group_by(station, month_year, Variable) %>%
  mutate(mean_month = ifelse(max(counter) >= 10,
                             mean(mean_daily, na.rm = TRUE),
                             NA_real_),
         mean_month = ifelse(is.nan(mean_month),
                             NA_real_,
                             mean_month),
         date = as.Date(paste0(month_year, "-1"))) %>% ## Create a dummy date variable for the first of each month
  select(month_year, date, station, Variable, mean_month) %>%
  distinct(.keep_all = TRUE)

dat_month %>% 
  filter(Variable == "DO_mgl") %>%
  ggplot(aes(date, mean_month))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 15)+
  labs(x = "Year", y = "Dissolved Oxygen Concentration (mg/L)") +
  facet_wrap(.~station, labeller = station_names) + ## This function makes identical plots across stations
  ## facet_grid(Variable ~ station, scales = "free") +
  ecodata::theme_ts()

# grbmonth %>% 
#   filter(Variable == "DO_mgl") %>% 
#   ggplot(aes(date, mean_daily))+
#   geom_point(color = "lightblue")+
#   geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
#   scale_x_date(date_labels = "%y", date_breaks = "1 year")+
#   ylim(0, 15)+
#   labs(x = "Year", y = "Dissolved Oxygen Concentration (mg/L)", title = "Great Bay")+
#   ecodata::theme_ts()
# 
# waqmonth %>% 
#   filter(Variable == "DO_mgl") %>% 
#   ggplot(aes(date, mean_daily))+
#   geom_point(color = "lightblue")+
#   geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
#   scale_x_date(date_labels = "%y", date_breaks = "1 year")+
#   ylim(0, 15)+
#   labs(x = "Year", y = "Dissolved Oxygen Concentration (mg/L)", title = "Waquoit Bay")+
#   ecodata::theme_ts()
# 
# welmonth %>% 
#   filter(Variable == "DO_mgl") %>% 
#   ggplot(aes(date, mean_daily))+
#   geom_point(color = "lightblue")+
#   geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
#   scale_x_date(date_labels = "%y", date_breaks = "1 year")+
#   ylim(0, 15)+
#   labs(x = "Year", y = "Dissolved Oxygen Concentration (mg/L)", title = "Wells Bay")+
#   ecodata::theme_ts()
```

### Only 2020

``` {r, message=FALSE, echo=FALSE, warning=FALSE, fig.show="hold", out.width="50%"}
narmonth %>% 
  filter(Variable == "DO_mgl") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(0, 15)+
  labs(x = "", y = "Dissolved Oxygen Concentration (mg/L)", title = "Narraganset")+
  ecodata::theme_ts()

grbmonth %>% 
  filter(Variable == "DO_mgl") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(0, 15)+
  labs(x = "", y = "Dissolved Oxygen Concentration (mg/L)", title = "Great Bay")+
  ecodata::theme_ts()

waqmonth %>% 
  filter(Variable == "DO_mgl") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(0, 15)+
  labs(x = "", y = "Dissolved Oxygen Concentration (mg/L)", title = "Waquoit Bay")+
  ecodata::theme_ts()

welmonth %>% 
  filter(Variable == "DO_mgl") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(0, 15)+
  labs(x = "", y = "Dissolved Oxygen Concentration (mg/L)", title = "Wells Bay")+
  ecodata::theme_ts()
```

## Dissolved Oxygen (%) {.tabset}

### All years

``` {r, message=FALSE, echo=FALSE, warning=FALSE, fig.show="hold", out.width="50%"}
nartsmonth %>% 
  filter(Variable == "DO_Pct") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(50, 120)+
  labs(x = "Year", y = "Dissolved Oxygen Concentration (% saturation)", title = "Narraganset") +
  ecodata::theme_ts()

grbmonth %>% 
  filter(Variable == "DO_Pct") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(50, 120)+
  labs(x = "Year", y = "Dissolved Oxygen Concentration (% saturation)", title = "Great Bay") +
  ecodata::theme_ts()

waqmonth %>% 
  filter(Variable == "DO_Pct") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(50, 120)+
  labs(x = "Year", y = "Dissolved Oxygen Concentration (% saturation)", title = "Waquoit Bay") +
  ecodata::theme_ts()

welmonth %>% 
  filter(Variable == "DO_Pct") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(50, 120)+
  labs(x = "Year", y = "Dissolved Oxygen Concentration (% saturation)", title = "Wells Bay") +
  ecodata::theme_ts()
```

### Only 2020

```{r, message=FALSE, echo=FALSE, warning=FALSE, fig.show="hold", out.width="50%"}
nartsmonth %>% 
  filter(Variable == "DO_Pct") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(50, 120)+
  labs(x = "", y = "Dissolved Oxygen Concentration (% saturation)", title = "Narraganset")+
  ecodata::theme_ts()

grbmonth %>% 
  filter(Variable == "DO_Pct") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(50, 120)+
  labs(x = "", y = "Dissolved Oxygen Concentration (% saturation)", title = "Great Bay")+
  ecodata::theme_ts()

waqmonth %>% 
  filter(Variable == "DO_Pct") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(50, 120)+
  labs(x = "", y = "Dissolved Oxygen Concentration (% saturation)", title = "Waquoit Bay")+
  ecodata::theme_ts()

welmonth %>% 
  filter(Variable == "DO_Pct") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(50, 120)+
  labs(x = "", y = "Dissolved Oxygen Concentration (% saturation)", title = "Wells Bay")+
  ecodata::theme_ts()
```

## Temperature {.tabset}

### All years

``` {r, message=FALSE, echo=FALSE, warning=FALSE, fig.show="hold", out.width="50%"}
nartsmonth %>% 
  filter(Variable == "Temp") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 30)+
  labs(x = "Year", y = "Temperature (C)", title = "Narraganset")+
  ecodata::theme_ts()

grbmonth %>% 
  filter(Variable == "Temp") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 30)+
  labs(x = "Year", y = "Temperature (C)", title = "Great Bay")+
  ecodata::theme_ts()

waqmonth %>% 
  filter(Variable == "Temp") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 30)+
  labs(x = "Year", y = "Temperature (C)", title = "Waquoit Bay")+
  ecodata::theme_ts()

welmonth %>% 
  filter(Variable == "Temp") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 30)+
  labs(x = "Year", y = "Temperature (C)", title = "Wells Bay")+
  ecodata::theme_ts()
```

### Only 2020

``` {r, message=FALSE, echo=FALSE, warning=FALSE, fig.show="hold", out.width="50%"}
nartsmonth %>% 
  filter(Variable == "Temp") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(0, 30)+
  labs(x = "", y = "Temperature (C)", title = "Narraganset")+
  ecodata::theme_ts()

grbmonth %>% 
  filter(Variable == "Temp") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(0, 30)+
  labs(x = "", y = "Temperature (C)", title = "Great Bay")+
  ecodata::theme_ts()

waqmonth %>% 
  filter(Variable == "Temp") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(0, 30)+
  labs(x = "", y = "Temperature (C)", title = "Waquoit Bay")+
  ecodata::theme_ts()

welmonth %>% 
  filter(Variable == "Temp") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(0, 30)+
  labs(x = "", y = "Temperature (C)", title = "Wells Bay")+
  ecodata::theme_ts()
```

## Salinity {.tabset}

### All years

``` {r, message=FALSE, echo=FALSE, warning=FALSE, fig.show="hold", out.width="50%"}
nartsmonth %>% 
  filter(Variable == "Sal") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 32)+
  labs(x = "Year", y = "Salnity (psu)", title = "Narraganset")+
  ecodata::theme_ts()

grbmonth %>% 
  filter(Variable == "Sal") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 32)+
  labs(x = "Year", y = "Salnity (psu)", title = "Great Bay")+
  ecodata::theme_ts()

waqmonth %>% 
  filter(Variable == "Sal") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 32)+
  labs(x = "Year", y = "Salnity (psu)", title = "Waquoit Bay")+
  ecodata::theme_ts()

welmonth %>% 
  filter(Variable == "Sal") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 32)+
  labs(x = "Year", y = "Salnity (psu)", title = "Wells Bay")+
  ecodata::theme_ts()
```

### Only 2020

```{r, message=FALSE, echo=FALSE, warning=FALSE, fig.show="hold", out.width="50%"}
nartsmonth %>% 
  filter(Variable == "Sal") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(0, 32)+
  labs(x = "", y = "Salinity (psu)", title = "Narraganset")+
  ecodata::theme_ts()

grbmonth %>% 
  filter(Variable == "Sal") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(0, 32)+
  labs(x = "", y = "Salinity (psu)", title = "Great Bay")+
  ecodata::theme_ts()

waqmonth %>% 
  filter(Variable == "Sal") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(0, 32)+
  labs(x = "", y = "Salinity (psu)", title = "Waquoit Bay")+
  ecodata::theme_ts()

welmonth %>% 
  filter(Variable == "Sal") %>% filter(date >= "2020-01-01") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%b", date_breaks = "1 month")+
  ylim(0, 32)+
  labs(x = "", y = "Salinity (psu)", title = "Wells Bay")+
  ecodata::theme_ts()
```

## Chlorophyll

```{r, message=FALSE, echo=FALSE, warning=FALSE, fig.show="hold", out.width="50%"}
chloro_nutri <- read_csv(here::here("data/nutrient_pep.csv"))
nartsnut <- chloro_nutri %>% filter(station == "nartsnut")
welnut <- chloro_nutri %>% filter(station == "welinnut")
grbnut <- chloro_nutri %>% filter(station == "grbgbnut") %>%
  mutate(date = as.Date(date))

nartsnut%>% 
  filter(Variable == "CHLA_N") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 10)+
  labs(x = "Year", y = "Chlorophyll concentration (µg/L)", title = "Narraganset")+
  ecodata::theme_ts()

grbnut%>% 
  filter(Variable == "CHLA_N") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 10)+
  labs(x = "Year", y = "Chlorophyll concentration (µg/L)", title = "Great Bay")+
  ecodata::theme_ts()

welnut%>% 
  filter(Variable == "CHLA_N") %>% 
  ggplot(aes(date, mean_daily))+
  geom_point(color = "lightblue")+
  geom_smooth(method = "loess", span = 0.08, color = "steelblue", se = F)+
  scale_x_date(date_labels = "%y", date_breaks = "1 year")+
  ylim(0, 10)+
  labs(x = "Year", y = "Chlorophyll concentration (µg/L)", title = "Wells Bay")+
  ecodata::theme_ts()
```