---
title: "Heatwave"
output: html_document
---



```{r, message=FALSE, echo=FALSE, warning=FALSE}
library(heatwaveR)
library(tidyverse)
library(readxl)
library(stringr)
library(readr)


nar_heatwave_csv<-"nar_heatwave.csv"
grb_heatwave_csv<-"grb_heatwave.csv"
wqb_heatwave_csv<-"wqb_heatwave.csv"
wel_heatwave_csv<-"wel_heatwave.csv"
raw.dir <- here::here("data")

```

# Heatwaves by station {.tabset}

## Narraganset

```{r, message=FALSE, echo=FALSE, warning=FALSE}
heatwave<-read_csv(file.path(raw.dir,nar_heatwave_csv), col_types = cols(temp = col_double(),t = col_date()))

ts <- heatwaveR::ts2clm(heatwave, climatologyPeriod = c("2007-07-21", "2020-12-29"))
nar.mhw <- heatwaveR::detect_event(ts)
  
nar_mhw<- nar.mhw$clim %>%
  mutate(Year = lubridate::year(t))

nar_mhw %>% 
  filter( Year == "2020") %>% 
  ggplot( aes(x = t, y = temp))+
  geom_flame(aes(y2 = thresh))+ 
  geom_line(aes(x = t, y = seas, color = "a"), size = 1)+
  geom_line(aes(x = t, y = thresh, color = "c"), size = 1)+
  geom_line(aes(x = t, y = temp, color = "b"))+
  scale_colour_manual(values = c("turquoise4", "sienna3", "black"),
                      labels = c("Climatology","Temperature", "Threshold"))+
  labs(x = "", y = "Temperature (C)", title = "Narragansett 2020 data")+
  scale_x_date(date_labels = "%b", breaks = "1 month")+
  theme_bw()+
  theme(legend.title = element_blank(),
        legend.position=c(0.2, 0.8))+
  ecodata::theme_title()




nar_mhw %>% 
  filter(Year == "2012") %>% 
  ggplot( aes(x = t, y = temp))+
  geom_flame(aes(y2 = thresh))+ 
  geom_line(aes(x = t, y = seas, color = "a"), size = 1)+
  geom_line(aes(x = t, y = thresh, color = "c"), size = 1)+
  geom_line(aes(x = t, y = temp, color = "b"))+
  scale_colour_manual(values = c("turquoise4", "sienna3", "black"),
                      labels = c("Climatology","Temperature", "Threshold"))+
  labs(x = "", y = "Temperature (C)", title = "Narragansett 2012 data")+
  scale_x_date(date_labels = "%b", breaks = "1 month")+
  theme_bw()+
  theme(legend.title = element_blank(),
        legend.position=c(0.2, 0.8))+
  ecodata::theme_title()
```


## Waquoit Bay 

```{r, message=FALSE, echo=FALSE, warning=FALSE}
heatwave<-read_csv(file.path(raw.dir,wqb_heatwave_csv), col_types = cols(temp = col_double(),t = col_date()))

ts <- heatwaveR::ts2clm(heatwave, climatologyPeriod = c("2007-01-02", "2020-12-09"))
wqb.mhw <- heatwaveR::detect_event(ts)
  
wqb_mhw<- wqb.mhw$clim %>%
  mutate(Year = lubridate::year(t))

wqb_mhw %>% 
  filter(Year == "2020") %>% 
  ggplot( aes(x = t, y = temp))+
  geom_flame(aes(y2 = thresh))+ 
  geom_line(aes(x = t, y = seas, color = "a"), size = 1)+
  geom_line(aes(x = t, y = thresh, color = "c"), size = 1)+
  geom_line(aes(x = t, y = temp, color = "b"))+
  scale_colour_manual(values = c("turquoise4", "sienna3", "black"),
                      labels = c("Climatology","Temperature", "Threshold"))+
  labs(x = "", y = "Temperature (C)", title = "Waquoit 2020 data")+
  scale_x_date(date_labels = "%b", breaks = "1 month")+
  theme_bw()+
  theme(legend.title = element_blank(),
        legend.position=c(0.2, 0.8))+
  ecodata::theme_title()




wqb_mhw %>% 
  filter(Year == "2012") %>% 
  ggplot( aes(x = t, y = temp))+
  geom_flame(aes(y2 = thresh))+ 
  geom_line(aes(x = t, y = seas, color = "a"), size = 1)+
  geom_line(aes(x = t, y = thresh, color = "c"), size = 1)+
  geom_line(aes(x = t, y = temp, color = "b"))+
  scale_colour_manual(values = c("turquoise4", "sienna3", "black"),
                      labels = c("Climatology","Temperature", "Threshold"))+
  labs(x = "", y = "Temperature (C)", title = "Waquoit 2012 data")+
  scale_x_date(date_labels = "%b", breaks = "1 month")+
  theme_bw()+
  theme(legend.title = element_blank(),
        legend.position=c(0.2, 0.8))+
  ecodata::theme_title()
```


## Great Bay 

```{r, message=FALSE, echo=FALSE, warning=FALSE}
heatwave<-read_csv(file.path(raw.dir,grb_heatwave_csv), col_types = cols(temp = col_double(),t = col_date()))

ts <- heatwaveR::ts2clm(heatwave, climatologyPeriod = c("2007-04-05", "2020-08-01"))
grb.mhw <- heatwaveR::detect_event(ts)
  
grb_mhw<- grb.mhw$clim %>%
  mutate(Year = lubridate::year(t))

grb_mhw %>% 
  filter(Year == "2020") %>% 
  ggplot( aes(x = t, y = temp))+
  geom_flame(aes(y2 = thresh))+ 
  geom_line(aes(x = t, y = seas, color = "a"), size = 1)+
  geom_line(aes(x = t, y = thresh, color = "c"), size = 1)+
  geom_line(aes(x = t, y = temp, color = "b"))+
  scale_colour_manual(values = c("turquoise4", "sienna3", "black"),
                      labels = c("Climatology","Temperature", "Threshold"))+
  labs(x = "", y = "Temperature (C)", title = "Great Bay 2020 data")+
  scale_x_date(date_labels = "%b", breaks = "1 month")+
  theme_bw()+
  theme(legend.title = element_blank(),
        legend.position=c(0.2, 0.8))+
  ecodata::theme_title()




grb_mhw %>% 
  filter( Year == "2012") %>% 
  ggplot( aes(x = t, y = temp))+
  geom_flame(aes(y2 = thresh))+ 
  geom_line(aes(x = t, y = seas, color = "a"), size = 1)+
  geom_line(aes(x = t, y = thresh, color = "c"), size = 1)+
  geom_line(aes(x = t, y = temp, color = "b"))+
  scale_colour_manual(values = c("turquoise4", "sienna3", "black"),
                      labels = c("Climatology","Temperature", "Threshold"))+
  labs(x = "", y = "Temperature (C)", title = "Great Bay 2012 data")+
  scale_x_date(date_labels = "%b", breaks = "1 month")+
  theme_bw()+
  theme(legend.title = element_blank(),
        legend.position=c(0.2, 0.8))+
  ecodata::theme_title()
```



## Wells Bay 

```{r, message=FALSE, echo=FALSE, warning=FALSE}
heatwave<-read_csv(file.path(raw.dir,wel_heatwave_csv), col_types = cols(temp = col_double(),t = col_date()))

ts <- heatwaveR::ts2clm(heatwave, climatologyPeriod = c("2007-01-26", "2020-12-28"))
wel.mhw <- heatwaveR::detect_event(ts)
  
wel_mhw<- wel.mhw$clim %>%
  mutate(Year = lubridate::year(t))

wel_mhw %>% 
  filter(Year == "2020") %>% 
  ggplot( aes(x = t, y = temp))+
  geom_flame(aes(y2 = thresh))+ 
  geom_line(aes(x = t, y = seas, color = "a"), size = 1)+
  geom_line(aes(x = t, y = thresh, color = "c"), size = 1)+
  geom_line(aes(x = t, y = temp, color = "b"))+
  scale_colour_manual(values = c("turquoise4", "sienna3", "black"),
                      labels = c("Climatology","Temperature", "Threshold"))+
  labs(x = "", y = "Temperature (C)", title = "Wells 2020 data")+
  scale_x_date(date_labels = "%b", breaks = "1 month")+
  theme_bw()+
  theme(legend.title = element_blank(),
        legend.position=c(0.2, 0.8))+
  ecodata::theme_title()


wel_mhw %>% 
  filter(Year == "2012") %>% 
  ggplot( aes(x = t, y = temp))+
  geom_flame(aes(y2 = thresh))+ 
  geom_line(aes(x = t, y = seas, color = "a"), size = 1)+
  geom_line(aes(x = t, y = thresh, color = "c"), size = 1)+
  geom_line(aes(x = t, y = temp, color = "b"))+
  scale_colour_manual(values = c("turquoise4", "sienna3", "black"),
                      labels = c("Climatology","Temperature", "Threshold"))+
  labs(x = "", y = "Temperature (C)", title = "Wells 2012 data")+
  scale_x_date(date_labels = "%b", breaks = "1 month")+
  theme_bw()+
  theme(legend.title = element_blank(),
        legend.position=c(0.2, 0.8))+
  ecodata::theme_title()
```






